packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

overrides:
  webpack: '5.105.0'
  '@module-federation/enhanced': '0.9.1'
  '@module-federation/manifest': '0.9.1'
  '@module-federation/sdk': '0.9.1'
  '@module-federation/runtime': '0.9.1'
  '@module-federation/node': '2.6.26'
  '@module-federation/node>@module-federation/enhanced': '0.9.1'
